version: '3.2'

services:
  www:
    build:
      context: ./docker/php-apache
      dockerfile: Dockerfile
    environment:
      GIT_AUTHOR_NAME: ${GIT_USER}
      GIT_AUTHOR_EMAIL: ${GIT_USER_EMAIL}
    ports:
      - ${HTTP_PORT}:80
    volumes:
      - ./docker/config/ssh/id_rsa:/root/.ssh/id_rsa:ro
      - ./docker/config/ssh/id_rsa.pub:/root/.ssh/id_rsa.pub:ro      
      - ./docker/config/php/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:ro
      - ./data/logs/:/var/logs/
      - ./data/ssh/known_hosts:/root/.ssh/known_hosts
      - ./:/root/repository
      - ./code:/var/www
    container_name: ${PROJECT_NAME}_www
  mysql:
    image: mysql:5.7
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: toor
    volumes:
      - ./data/mysql:/var/lib/mysql
    container_name: ${PROJECT_NAME}_mysql