version: '3.2'

services:
  www:
    build:
      context: ./docker/php-apache
      dockerfile: Dockerfile
    ports:
      - ${HTTP_PORT}:80
    volumes: 
      - ./code/www:/var/www
      - ./docker/ssh:/root/.ssh:ro
      - ./:/root/repository
    container_name: ${PROJECT_NAME}_www
  mysql:
    image: mysql:5.7
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: toor
    volumes:
      - ./data/mysql:/var/lib/mysql
    container_name: ${PROJECT_NAME}_mysql